name: easy-fashion

services:
  postgres:
    image: postgres:16-alpine
    container_name: easy-fashion-postgres-prod
    env_file:
      - .env
    volumes:
      - /var/lib/easy-fashion/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-easy-fashion}']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/nishan-paul-2022/easy-fashion-backend:latest
    container_name: easy-fashion-backend-prod
    env_file:
      - .env
    ports:
      - '3015:3015'
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  customer:
    image: ghcr.io/nishan-paul-2022/easy-fashion-customer:latest
    container_name: easy-fashion-customer-prod
    env_file:
      - .env
    ports:
      - '3013:3000'
    restart: unless-stopped

  management:
    image: ghcr.io/nishan-paul-2022/easy-fashion-management:latest
    container_name: easy-fashion-management-prod
    env_file:
      - .env
    ports:
      - '3014:3000'
    restart: unless-stopped

volumes:
  postgres_data:
